### ISSUE TITLE
Input HDF5 file for repop mode should be in the "data" folder

### ISSUE THREAD

**Issue by binnympaul** [RSGInc/populationsim#33]
Currently, input HDF5 file from base run for the repop mode is copied to the "output" folder. This should be changed to "output" folder, the user should copy the HDF5 file to the "output" folder of the repop setup.

**Comment by toliwaga** [comment]
This will be rather a lot of effort.

**Comment by toliwaga** [comment]
Right now, repop is implemented using the resume_after feature of the data pipeline. The resume_after feature reads its inputs from the HDF5 output file in the output folder.

If we do what this issue suggests, we will need to write custom code to handle this, possibly changing the activitysim pipeline code.

**Comment by binnympaul** [comment]
What do you feel about having the batch interface copy the HDF5 from the inputs folder to output folder before launching the run?

**Comment by bstabler** [comment]
The batch files are not really part of the software, so I don't really like that idea as an official fix.  Maybe the software could simply copy the hdf5 file from inputs if mode=repop?  We could also maybe just add to the user's guide that the hdf5 file goes in the outputs folder since it is an output from a previous run.

**Comment by binnympaul** [comment]
OK, sounds good to me. I can make changes to the user guide if software changes are difficult.
